apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu
  namespace: kube-system
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: application/ubuntu
    repoURL: https://github.com/axivo/charts.git
    targetRevision: ubuntu-v2.1.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
