title: AXIVO Charts
description: Helm charts optimized for ArgoCD deployments
keywords: argocd, kubernetes, helm, chart, container, devops
url: https://axivo.github.io
baseurl: /charts
timezone: America/New_York
github:
  is_project_page: true
  repository_url: https://github.com/axivo/charts
  show_downloads: false

# Jekyll build settings
theme: jekyll-theme-primer
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata

# Jekyll custom head configuration
head: >
  <style>
    div.footer { display: none !important; }
  </style>
