apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: application/sealed-secrets
    repoURL: https://github.com/axivo/charts.git
    targetRevision: sealed-secrets-1.0.4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
