name: Chart

on:
  pull_request:
    paths:
      - application/*/Chart.yaml
      - application/*/README.md.gotmpl
      - application/*/values.yaml
      - library/*/Chart.yaml
      - library/*/README.md.gotmpl
      - library/*/values.yaml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version: stable

      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.3

      - name: Install helm-docs
        run: go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.14.2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install node dependencies
        run: npm install js-yaml handlebars

      - name: Configure repository
        uses: actions/github-script@v7
        with:
          script: |
            const { configureGit } = require('./.github/scripts/git-config.js');
            await configureGit({ github, context, core, exec });

      - name: Update documentation
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { updateDocumentation } = require('./.github/scripts/documentation.js');
            await updateDocumentation({ github, context, core, exec });

      - name: Update dependency lock files
        uses: actions/github-script@v7
        with:
          script: |
            const { updateLockFiles } = require('./.github/scripts/pages.js');
            await updateLockFiles({ github, context, core, exec });
