name: Release

on:
  push:
    branches:
      - main
    paths:
      - .github/templates/*
      - application/**
      - library/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  checks: write
  contents: write
  id-token: write
  issues: write
  packages: write
  pages: write

jobs:
  distribution:
    name: Distribution
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node dependencies
        run: npm install glob handlebars js-yaml

      - name: Configure repository
        id: workflow
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.configureRepository();

      - name: Setup repository charts linter
        uses: helm/chart-testing-action@v2

      - name: Process chart releases
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.processReleases();

      - name: Setup frontpage
        if: steps.workflow.outputs.publish == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.setFrontpage();

      - name: Build pages
        if: steps.workflow.outputs.publish == 'true'
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Configure pages
        if: steps.workflow.outputs.publish == 'true'
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        if: steps.workflow.outputs.publish == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy pages
        if: steps.workflow.outputs.publish == 'true'
        uses: actions/deploy-pages@v4

      - name: Report workflow issue
        uses: actions/github-script@v7
        if: always()
        with:
          script: |
            const { Workflow } = require('./.github/actions/handlers');
            const workflow = new Workflow({ github, context, core, exec });
            await workflow.reportIssue();
