theme: jekyll-theme-primer
title: AXIVO
description: Helm charts optimized for ArgoCD deployments
url: https://axivo.github.io
baseurl: /charts
timezone: America/New_York
github:
  license:
    name: BSD-3-Clause
  repository_url: https://github.com/axivo/charts
  show_downloads: false
exclude:
  - application/*/README.md
  - library/*/README.md
  - node_modules
  - script
include:
  - application/*/index.yaml
  - library/*/index.yaml
